baseurl = "https://ladrift.github.io/"
languageCode = "en-US"
title = "ladrift"

theme = "after-dark"
paginate = 5

SectionPagesMenu = "main"
enableRobotsTXT = true

[params]
    author = "Ziyi Yan"
    description = "Code, thoughts and life."
    powered_by = false

[menu]
    [[menu.main]]
        name = "Home"
        weight = 0
        identifier = "home"
        url = "/"
    [[menu.main]]
        name = "Posts"
        weight = 1
        identifier = "post"
        url = "/post/"
