# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "gindoro"
license = "MIT"
licenselink = "https://github.com/cdipaolo/gindoro/blob/master/LICENSE.md"
description = "minimalistic and _extremely_ lightweight hugo theme"
homepage = "http://dipaolo.conner.sh/"
tags = ["minimal", "hugo", "lightweight", "low-latency"]
features = ["very lightweight", "renders really, really quickly", "super minimal"]
min_version = 0.13

[author]
  name = "Conner DiPaolo"
  homepage = "http://dipaolo.conner.sh"
